# Generated by Django 4.2.20 on 2025-03-24 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_processo_document_stored'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processo',
            name='user',
        ),
        migrations.DeleteModel(
            name='CitiusAccount',
        ),
        migrations.DeleteModel(
            name='Processo',
        ),
    ]
