# Generated by Django 4.2.20 on 2025-03-26 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_remove_processo_user_delete_citiusaccount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('nif', models.CharField(blank=True, max_length=50, null=True, verbose_name='NIFP')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefone')),
                ('address', models.CharField(blank=True, null=True, verbose_name='Morada')),
                ('monthly_fee', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Avença Mensal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('account_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_managed', to=settings.AUTH_USER_MODEL, verbose_name='Gestor de Conta')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('in_progress', 'Em Progresso'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='Status')),
                ('priority', models.IntegerField(choices=[(1, 'Urgente'), (2, 'Alta'), (3, 'Média'), (4, 'Baixa'), (5, 'Pode Esperar')], default=3, verbose_name='Prioridade')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Prazo')),
                ('estimated_time_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tempo Estimado (minutos)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Concluída em')),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Atribuído a')),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'ordering': ['priority', 'deadline'],
            },
        ),
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('color', models.CharField(default='#3498db', max_length=7, verbose_name='Cor')),
                ('average_time_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tempo Médio (minutos)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Categoria de Tarefa',
                'verbose_name_plural': 'Categorias de Tarefas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(verbose_name='Descrição')),
                ('minutes_spent', models.PositiveIntegerField(verbose_name='Minutos Gastos')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Data')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Hora de Início')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Hora de Término')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('original_text', models.TextField(blank=True, null=True, verbose_name='Texto Original')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.taskcategory', verbose_name='Categoria')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='api.client', verbose_name='Cliente')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to='api.task', verbose_name='Tarefa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Registro de Tempo',
                'verbose_name_plural': 'Registros de Tempo',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='api.taskcategory', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='task',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.client', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço à Hora')),
                ('role', models.CharField(max_length=100, verbose_name='Função')),
                ('access_level', models.CharField(max_length=100, verbose_name='Nível de Acesso')),
                ('phone', models.CharField(max_length=100, verbose_name='Telefone')),
                ('productivity_metrics', models.JSONField(default=dict, verbose_name='Métricas de Produtividade')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Categoria')),
                ('date', models.DateField(verbose_name='Data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('is_auto_categorized', models.BooleanField(default=False, verbose_name='Categorizado Automaticamente')),
                ('source', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fonte')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='api.client', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ClientProfitability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField(verbose_name='Ano')),
                ('month', models.IntegerField(verbose_name='Mês')),
                ('total_time_minutes', models.PositiveIntegerField(default=0, verbose_name='Tempo Total (minutos)')),
                ('time_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Custo do Tempo')),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Despesas Totais')),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Avença Mensal')),
                ('profit', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Lucro')),
                ('profit_margin', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Margem de Lucro (%)')),
                ('is_profitable', models.BooleanField(null=True, verbose_name='É Rentável')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profitability_records', to='api.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Rentabilidade de Cliente',
                'verbose_name_plural': 'Rentabilidades de Clientes',
                'ordering': ['-year', '-month', 'client__name'],
                'unique_together': {('client', 'year', 'month')},
            },
        ),
    ]
