# Generated by Django 4.2.20 on 2025-03-30 22:39

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0011_alter_profile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='NLPProcessor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pattern', models.CharField(max_length=500, verbose_name='Padrão')),
                ('entity_type', models.CharField(max_length=100, verbose_name='Tipo de Entidade')),
                ('confidence', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Confiança')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='Contador de Uso')),
            ],
            options={
                'verbose_name': 'Processador NLP',
                'verbose_name_plural': 'Processadores NLP',
                'ordering': ['-usage_count', '-confidence'],
            },
        ),
        migrations.CreateModel(
            name='AutoTimeTracking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(verbose_name='Hora de Início')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Hora de Término')),
                ('activity_data', models.JSONField(default=dict, verbose_name='Dados de Atividade')),
                ('processed', models.BooleanField(default=False, verbose_name='Processado')),
                ('converted_to_entries', models.JSONField(default=list, verbose_name='Convertido em Registros')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_time_tracking', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Rastreamento Automático',
                'verbose_name_plural': 'Rastreamentos Automáticos',
                'ordering': ['-start_time'],
            },
        ),
    ]
