# Generated by Django 4.2.20 on 2025-03-30 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0012_nlpprocessor_autotimetracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflows', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Definição de Fluxo de Trabalho',
                'verbose_name_plural': 'Definições de Fluxo de Trabalho',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='workflow_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comentário do Fluxo'),
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('order', models.PositiveIntegerField(verbose_name='Ordem')),
                ('requires_approval', models.BooleanField(default=False, verbose_name='Requer Aprovação')),
                ('approver_role', models.CharField(blank=True, max_length=100, null=True, verbose_name='Papel do Aprovador')),
                ('next_steps', models.JSONField(default=list, help_text='List of possible next step IDs', verbose_name='Próximos Passos')),
                ('previous_steps', models.JSONField(default=list, help_text='List of possible previous step IDs', verbose_name='Passos Anteriores')),
                ('assign_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_workflow_steps', to=settings.AUTH_USER_MODEL, verbose_name='Atribuir a')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='api.workflowdefinition', verbose_name='Fluxo de Trabalho')),
            ],
            options={
                'verbose_name': 'Passo de Fluxo de Trabalho',
                'verbose_name_plural': 'Passos de Fluxo de Trabalho',
                'ordering': ['workflow', 'order'],
                'unique_together': {('workflow', 'order')},
            },
        ),
        migrations.AddField(
            model_name='task',
            name='current_workflow_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_tasks', to='api.workflowstep', verbose_name='Passo Atual do Fluxo'),
        ),
        migrations.AddField(
            model_name='task',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='api.workflowdefinition', verbose_name='Fluxo de Trabalho'),
        ),
        migrations.CreateModel(
            name='TaskApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('approved_at', models.DateTimeField(auto_now_add=True, verbose_name='Aprovado em')),
                ('approved', models.BooleanField(default=True, verbose_name='Aprovado')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comentário')),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_approvals', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='api.task', verbose_name='Tarefa')),
                ('workflow_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_approvals', to='api.workflowstep', verbose_name='Passo do Fluxo')),
            ],
            options={
                'verbose_name': 'Aprovação de Tarefa',
                'verbose_name_plural': 'Aprovações de Tarefas',
                'ordering': ['-approved_at'],
                'unique_together': {('task', 'workflow_step', 'approved_by')},
            },
        ),
    ]
