# Generated by Django 4.2.20 on 2025-04-03 16:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_workflowdefinition_task_workflow_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Morada')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de Contacto')),
                ('logo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Logo URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('subscription_plan', models.CharField(blank=True, max_length=50, null=True, verbose_name='Plano de Subscrição')),
                ('max_users', models.PositiveIntegerField(default=5, verbose_name='Máximo de Utilizadores')),
                ('settings', models.JSONField(default=dict, verbose_name='Configurações')),
            ],
            options={
                'verbose_name': 'Organização',
                'verbose_name_plural': 'Organizações',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='can_assign_tasks',
            field=models.BooleanField(default=False, verbose_name='Pode Atribuir Tarefas'),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_manage_clients',
            field=models.BooleanField(default=False, verbose_name='Pode Gerir Clientes'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_org_admin',
            field=models.BooleanField(default=False, verbose_name='Administrador da Organização'),
        ),
        migrations.AddField(
            model_name='client',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='api.organization', verbose_name='Organização'),
        ),
        migrations.AddField(
            model_name='profile',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.organization', verbose_name='Organização'),
        ),
    ]
