# Generated by Django 4.2.20 on 2025-04-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_organization_profile_can_assign_tasks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='can_view_all_clients',
            field=models.BooleanField(default=False, verbose_name='Pode Ver Todos os Clientes'),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_view_analytics',
            field=models.BooleanField(default=False, verbose_name='Pode Ver Análises'),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_view_profitability',
            field=models.BooleanField(default=False, verbose_name='Pode Ver Rentabilidade'),
        ),
        migrations.AddField(
            model_name='profile',
            name='visible_clients',
            field=models.ManyToManyField(blank=True, related_name='visible_to_profiles', to='api.client', verbose_name='Clientes Visíveis'),
        ),
    ]
