# Generated by Django 4.2.20 on 2025-05-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_profile_can_view_all_clients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='invitation_code',
            field=models.CharField(default=9999, help_text='Código de 4 dígitos para adicionar este utilizador a uma organização', max_length=4, verbose_name='Código de Convite'),
            preserve_default=False,
        ),
    ]
