# Generated by Django 4.2.20 on 2025-05-15 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_profile_can_approve_tasks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='can_manage_workflows',
            field=models.BooleanField(default=False, verbose_name='Pode Gerenciar Workflows'),
        ),
    ]
