# Generated by Django 4.2.20 on 2025-05-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_profile_can_manage_workflows'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='task_status_after',
            field=models.CharField(choices=[('no_change', 'Sem alteração'), ('in_progress', 'Em Progresso'), ('completed', 'Concluída')], default='no_change', max_length=20, verbose_name='Status da Tarefa Após Registro'),
        ),
    ]
