# Generated by Django 4.2.21 on 2025-05-29 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0019_timeentry_task_status_after'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='advance_workflow',
            field=models.BooleanField(default=False, verbose_name='Avançar Workflow'),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='workflow_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to='api.workflowstep', verbose_name='Passo do Workflow'),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='workflow_step_completed',
            field=models.BooleanField(default=False, verbose_name='Passo do Workflow Concluído'),
        ),
        migrations.CreateModel(
            name='WorkflowNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('step_assigned', 'Passo Atribuído'), ('step_ready', 'Passo Pronto para Execução'), ('step_completed', 'Passo Concluído'), ('approval_needed', 'Aprovação Necessária'), ('approval_completed', 'Aprovação Concluída'), ('workflow_completed', 'Workflow Concluído')], max_length=50, verbose_name='Tipo de Notificação')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lida')),
                ('email_sent', models.BooleanField(default=False, verbose_name='Email Enviado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lida em')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_notifications', to='api.task', verbose_name='Tarefa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('workflow_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.workflowstep', verbose_name='Passo do Workflow')),
            ],
            options={
                'verbose_name': 'Notificação de Workflow',
                'verbose_name_plural': 'Notificações de Workflow',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('step_started', 'Passo Iniciado'), ('step_completed', 'Passo Concluído'), ('step_approved', 'Passo Aprovado'), ('step_rejected', 'Passo Rejeitado'), ('workflow_assigned', 'Workflow Atribuído'), ('workflow_completed', 'Workflow Concluído')], max_length=50, verbose_name='Ação')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comentário')),
                ('time_spent_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tempo Gasto (minutos)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_changes', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
                ('from_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_from', to='api.workflowstep', verbose_name='Passo Anterior')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_history', to='api.task', verbose_name='Tarefa')),
                ('to_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_to', to='api.workflowstep', verbose_name='Passo Seguinte')),
            ],
            options={
                'verbose_name': 'Histórico de Workflow',
                'verbose_name_plural': 'Históricos de Workflow',
                'ordering': ['-created_at'],
            },
        ),
    ]
