# Generated by Django 4.2.21 on 2025-06-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_timeentry_advance_workflow_timeentry_workflow_step_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowhistory',
            name='action',
            field=models.CharField(choices=[('step_started', 'Passo Iniciado'), ('step_work_logged', 'Trabalho Registrado no Passo'), ('step_completed', 'Passo Concluído'), ('step_advanced', 'Passo Avançado'), ('step_approved', 'Passo Aprovado'), ('step_rejected', 'Passo Rejeitado'), ('workflow_assigned', 'Workflow Atribuído'), ('workflow_completed', 'Workflow Concluído')], max_length=50, verbose_name='Ação'),
        ),
    ]
