# Generated by Django 4.2.21 on 2025-06-03 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0021_alter_workflowhistory_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflownotification',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='workflownotification',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Arquivada'),
        ),
        migrations.AddField(
            model_name='workflownotification',
            name='metadata',
            field=models.JSONField(default=dict, help_text='Dados adicionais da notificação', verbose_name='Metadados'),
        ),
        migrations.AddField(
            model_name='workflownotification',
            name='priority',
            field=models.CharField(choices=[('low', 'Baixa'), ('normal', 'Normal'), ('high', 'Alta'), ('urgent', 'Urgente')], default='normal', max_length=10, verbose_name='Prioridade'),
        ),
        migrations.AddField(
            model_name='workflownotification',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Agendada para'),
        ),
        migrations.AlterField(
            model_name='workflownotification',
            name='notification_type',
            field=models.CharField(choices=[('step_assigned', 'Passo Atribuído'), ('step_ready', 'Passo Pronto para Execução'), ('step_completed', 'Passo Concluído'), ('approval_needed', 'Aprovação Necessária'), ('approval_completed', 'Aprovação Concluída'), ('workflow_completed', 'Workflow Concluído'), ('deadline_approaching', 'Prazo Próximo'), ('step_overdue', 'Passo Atrasado'), ('manual_reminder', 'Lembrete Manual'), ('workflow_assigned', 'Workflow Atribuído'), ('step_rejected', 'Passo Rejeitado')], max_length=50, verbose_name='Tipo de Notificação'),
        ),
        migrations.AlterField(
            model_name='workflownotification',
            name='workflow_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.workflowstep', verbose_name='Passo do Workflow'),
        ),
        migrations.AddIndex(
            model_name='workflownotification',
            index=models.Index(fields=['user', 'is_read'], name='api_workflo_user_id_c4fe5d_idx'),
        ),
        migrations.AddIndex(
            model_name='workflownotification',
            index=models.Index(fields=['task', 'notification_type'], name='api_workflo_task_id_d7a510_idx'),
        ),
        migrations.AddIndex(
            model_name='workflownotification',
            index=models.Index(fields=['created_at'], name='api_workflo_created_e51f03_idx'),
        ),
    ]
