# Generated by Django 4.2.22 on 2025-06-09 17:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_notificationdigest_notificationtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='fiscal_tags',
            field=models.JSONField(blank=True, default=list, help_text="Usado para identificar a que obrigações este cliente está sujeito. Ex: ['EMPRESA', 'IVA_TRIMESTRAL', 'REGIME_GERAL_IRC']", verbose_name='Tags Fiscais do Cliente'),
        ),
        migrations.CreateModel(
            name='FiscalObligationDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nome da Obrigação')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição Detalhada')),
                ('periodicity', models.CharField(choices=[('MONTHLY', 'Mensal'), ('QUARTERLY', 'Trimestral'), ('ANNUAL', 'Anual'), ('BIANNUAL', 'Semestral'), ('OTHER', 'Outra')], max_length=20, verbose_name='Periodicidade')),
                ('calculation_basis', models.CharField(choices=[('END_OF_PERIOD', 'Fim do Período de Referência'), ('SPECIFIC_DATE', 'Data Específica no Ano'), ('EVENT_DRIVEN', 'Após um Evento')], default='END_OF_PERIOD', max_length=20, verbose_name='Base de Cálculo do Prazo')),
                ('deadline_day', models.PositiveIntegerField(help_text='Ex: 20 para o dia 20', verbose_name='Dia Limite do Mês para Entrega/Pagamento')),
                ('deadline_month_offset', models.PositiveIntegerField(default=0, help_text='0 para o mesmo mês, 1 para o mês seguinte, etc.', verbose_name='Offset de Meses para Deadline')),
                ('specific_month_reference', models.PositiveIntegerField(blank=True, help_text='Para obrigações com uma data base anual ou um mês específico de início de contagem.', null=True, verbose_name='Mês de Referência Específico (1-12)')),
                ('applies_to_client_tags', models.JSONField(blank=True, default=list, help_text="Lista de tags que o cliente deve ter. Ex: ['EMPRESA', 'IVA_MENSAL']", verbose_name='Aplica-se a Clientes com Tags')),
                ('default_task_title_template', models.CharField(default='{obligation_name} - {client_name} - {period_description}', help_text='Variáveis: {obligation_name}, {client_name}, {period_description}, {year}, {month_name}, {quarter}', max_length=255, verbose_name='Template do Título da Tarefa')),
                ('default_priority', models.IntegerField(choices=[(1, 'Urgente'), (2, 'Alta'), (3, 'Média'), (4, 'Baixa'), (5, 'Pode Esperar')], default=2, verbose_name='Prioridade Padrão da Tarefa')),
                ('generation_trigger_offset_days', models.IntegerField(default=30, verbose_name='Criar Tarefa X Dias Antes do Deadline')),
                ('is_active', models.BooleanField(default=True, verbose_name='Definição Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_task_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.taskcategory', verbose_name='Categoria de Tarefa Padrão')),
                ('default_workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.workflowdefinition', verbose_name='Workflow Padrão')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_obligation_definitions', to='api.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Definição de Obrigação Fiscal',
                'verbose_name_plural': 'Definições de Obrigações Fiscais',
                'ordering': ['name'],
            },
        ),
    ]
