# Generated by Django 4.2.22 on 2025-06-09 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_client_fiscal_tags_fiscalobligationdefinition'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='obligation_period_key',
            field=models.CharField(blank=True, help_text='Identificador único para o período desta obrigação (ex: ANO-TRIMESTRE)', max_length=50, null=True, verbose_name='Chave do Período da Obrigação'),
        ),
        migrations.AddField(
            model_name='task',
            name='source_fiscal_obligation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_tasks', to='api.fiscalobligationdefinition', verbose_name='Origem da Obrigação Fiscal'),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('client', 'source_fiscal_obligation', 'obligation_period_key')},
        ),
    ]
