# Generated by Django 4.2.21 on 2025-06-11 13:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_task_obligation_period_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalSystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_generation_enabled', models.BooleanField(default=True, verbose_name='Geração Automática Ativada')),
                ('generation_time', models.TimeField(default=datetime.time(8, 0), verbose_name='Horário da Geração Automática')),
                ('months_ahead_generation', models.PositiveIntegerField(default=3, verbose_name='Meses Futuros para Gerar')),
                ('auto_cleanup_enabled', models.BooleanField(default=True, verbose_name='Limpeza Automática Ativada')),
                ('cleanup_days_threshold', models.PositiveIntegerField(default=30, verbose_name='Dias para Considerar Obsoleto')),
                ('notify_on_generation', models.BooleanField(default=True, verbose_name='Notificar ao Gerar')),
                ('notify_on_errors', models.BooleanField(default=True, verbose_name='Notificar em Erros')),
                ('email_notifications_enabled', models.BooleanField(default=True, verbose_name='Notificações por Email')),
                ('notification_recipients', models.JSONField(default=list, help_text='Lista de emails para receber notificações', verbose_name='Destinatários de Notificação')),
                ('webhook_url', models.URLField(blank=True, help_text='URL para receber notificações via webhook', null=True, verbose_name='URL do Webhook')),
                ('webhook_secret', models.CharField(blank=True, max_length=255, null=True, verbose_name='Segredo do Webhook')),
                ('advanced_settings', models.JSONField(default=dict, help_text='Configurações adicionais em formato JSON', verbose_name='Configurações Avançadas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_generation', models.DateTimeField(blank=True, null=True, verbose_name='Última Geração')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_settings', to='api.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Configurações do Sistema Fiscal',
                'verbose_name_plural': 'Configurações do Sistema Fiscal',
            },
        ),
    ]
