# Generated by Django 4.2.21 on 2025-06-13 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_notificationsettings_notify_manual_advance_needed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowstep',
            name='next_steps',
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='next_steps',
            field=models.ManyToManyField(blank=True, related_name='previous_steps_rel', to='api.workflowstep', verbose_name='Próximos Passos'),
        ),
    ]
