# Generated by Django 4.2.21 on 2025-06-15 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_fiscalobligationdefinition_custom_rule_trigger_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowstep',
            name='next_steps',
        ),
        migrations.RemoveField(
            model_name='workflowstep',
            name='previous_steps',
        ),
    ]
