# Generated by Django 4.2.21 on 2025-06-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_clean_workflowstep_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstep',
            name='next_steps',
            field=models.ManyToManyField(blank=True, related_name='previous_steps_rel', to='api.workflowstep', verbose_name='Próximos Passos'),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='previous_steps',
            field=models.JSONField(default=list, help_text='List of possible previous step IDs', verbose_name='Passos Anteriores'),
        ),
    ]
