# Generated by Django 4.2.21 on 2025-06-15 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_add_workflow_step_relationships'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowstep',
            name='next_steps',
        ),
    ]
