# Generated by Django 4.2.21 on 2025-06-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_remove_workflowstep_next_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstep',
            name='next_steps',
            field=models.ManyToManyField(blank=True, help_text='Passos que podem ser executados após este passo', related_name='previous_steps', to='api.workflowstep', verbose_name='Próximos Passos'),
        ),
    ]
