# Generated by Django 4.2.21 on 2025-06-16 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_workflowstep_next_steps'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NLPProcessor',
        ),
    ]
