# Generated by Django 4.2.21 on 2025-06-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_delete_nlpprocessor'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='workflow_step_assignments',
            field=models.JSONField(blank=True, default=dict, help_text="Mapeamento de step_id para user_id. Ex: {'step_id_1': user_id_A, 'step_id_2': user_id_B}", verbose_name='Atribuições de Passos do Workflow'),
        ),
    ]
