# Generated by Django 4.2.21 on 2025-06-18 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0040_notificationsettings_notify_task_assigned_to_you_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Relatório')),
                ('report_type', models.CharField(choices=[('client_summary', 'Resumo de Cliente(s)'), ('profitability_analysis', 'Análise de Rentabilidade'), ('task_performance', 'Performance de Tarefas'), ('time_tracking_summary', 'Resumo de Registo de Tempos'), ('custom_report', 'Relatório Personalizado')], max_length=50, verbose_name='Tipo de Relatório')),
                ('report_format', models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV'), ('xlsx', 'Excel (XLSX)')], default='pdf', max_length=10, verbose_name='Formato')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Geração')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='Parâmetros Usados')),
                ('storage_url', models.URLField(max_length=1024, verbose_name='URL de Armazenamento (Supabase)')),
                ('file_size_kb', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tamanho (KB)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição Curta')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reports_meta', to=settings.AUTH_USER_MODEL, verbose_name='Gerado por')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to='api.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Relatório Gerado',
                'verbose_name_plural': 'Relatórios Gerados',
                'ordering': ['-created_at'],
            },
        ),
    ]
