# Generated by Django 4.2.21 on 2025-06-18 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0041_generatedreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedreport',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reports_meta', to=settings.AUTH_USER_MODEL, verbose_name='Gerado por'),
        ),
    ]
