# Generated by Django 4.2.21 on 2025-06-19 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_alter_generatedreport_generated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtemplate',
            name='notification_type',
            field=models.CharField(choices=[('step_assigned', 'Passo Atribuído'), ('step_ready', 'Passo Pronto para Execução'), ('step_completed', 'Passo Concluído'), ('approval_needed', 'Aprovação Necessária'), ('approval_completed', 'Aprovação Concluída'), ('task_completed', 'Tarefa Concluída'), ('task_assigned_to_you', 'Nova Tarefa Atribuída a Si'), ('deadline_approaching', 'Prazo Próximo'), ('step_overdue', 'Passo Atrasado'), ('manual_reminder', 'Lembrete Manual'), ('workflow_assigned', 'Workflow Atribuído'), ('step_rejected', 'Passo Rejeitado'), ('manual_advance_needed', 'Avanço Manual Necessário'), ('report_generated', 'Relatório Gerado')], max_length=50, verbose_name='Tipo de Notificação'),
        ),
        migrations.AlterField(
            model_name='workflownotification',
            name='metadata',
            field=models.JSONField(default=dict, help_text="Dados adicionais da notificação (e.g., report_id for 'report_generated')", verbose_name='Metadados'),
        ),
        migrations.AlterField(
            model_name='workflownotification',
            name='notification_type',
            field=models.CharField(choices=[('step_assigned', 'Passo Atribuído'), ('step_ready', 'Passo Pronto para Execução'), ('step_completed', 'Passo Concluído'), ('approval_needed', 'Aprovação Necessária'), ('approval_completed', 'Aprovação Concluída'), ('task_completed', 'Tarefa Concluída'), ('task_assigned_to_you', 'Nova Tarefa Atribuída a Si'), ('deadline_approaching', 'Prazo Próximo'), ('step_overdue', 'Passo Atrasado'), ('manual_reminder', 'Lembrete Manual'), ('workflow_assigned', 'Workflow Atribuído'), ('step_rejected', 'Passo Rejeitado'), ('manual_advance_needed', 'Avanço Manual Necessário'), ('report_generated', 'Relatório Gerado')], max_length=50, verbose_name='Tipo de Notificação'),
        ),
        migrations.AlterField(
            model_name='workflownotification',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_notifications', to='api.task', verbose_name='Tarefa'),
        ),
    ]
