# Generated by Django 4.2.21 on 2025-06-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_alter_notificationtemplate_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsettings',
            name='notify_report_generated',
            field=models.BooleanField(default=True),
        ),
    ]
