# Generated by Django 4.2.21 on 2025-06-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_notificationsettings_notify_report_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='invitation_code',
            field=models.CharField(help_text='Código de 4 dígitos para adicionar este utilizador a uma organização', max_length=4, unique=True, verbose_name='Código de Convite'),
        ),
    ]
