# Generated by Django 4.2.21 on 2025-06-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_alter_profile_invitation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedreport',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('IN_PROGRESS', 'Em Progresso'), ('COMPLETED', 'Concluído'), ('FAILED', 'Falhou')], db_index=True, default='PENDING', max_length=20, verbose_name='Status de Geração'),
        ),
        migrations.AlterField(
            model_name='generatedreport',
            name='storage_url',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='URL de Armazenamento'),
        ),
    ]
