# Generated by Django 4.2.21 on 2025-06-25 18:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_generatedreport_status_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='workflownotification',
            name='api_workflo_user_id_c4fe5d_idx',
        ),
        migrations.AlterField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='fiscalobligationdefinition',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Definição Ativa'),
        ),
        migrations.AlterField(
            model_name='generatedreport',
            name='report_type',
            field=models.CharField(choices=[('client_summary', 'Resumo de Cliente(s)'), ('profitability_analysis', 'Análise de Rentabilidade'), ('task_performance', 'Performance de Tarefas'), ('time_tracking_summary', 'Resumo de Registo de Tempos'), ('custom_report', 'Relatório Personalizado')], db_index=True, max_length=50, verbose_name='Tipo de Relatório'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Concluída em'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Prazo'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('in_progress', 'Em Progresso'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], db_index=True, default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='workflownotification',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Arquivada'),
        ),
        migrations.AlterField(
            model_name='workflownotification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Lida'),
        ),
        migrations.AlterField(
            model_name='workflownotification',
            name='notification_type',
            field=models.CharField(choices=[('step_assigned', 'Passo Atribuído'), ('step_ready', 'Passo Pronto para Execução'), ('step_completed', 'Passo Concluído'), ('approval_needed', 'Aprovação Necessária'), ('approval_completed', 'Aprovação Concluída'), ('task_completed', 'Tarefa Concluída'), ('task_assigned_to_you', 'Nova Tarefa Atribuída a Si'), ('deadline_approaching', 'Prazo Próximo'), ('step_overdue', 'Passo Atrasado'), ('manual_reminder', 'Lembrete Manual'), ('workflow_assigned', 'Workflow Atribuído'), ('step_rejected', 'Passo Rejeitado'), ('manual_advance_needed', 'Avanço Manual Necessário'), ('report_generated', 'Relatório Gerado')], db_index=True, max_length=50, verbose_name='Tipo de Notificação'),
        ),
        migrations.AddIndex(
            model_name='workflownotification',
            index=models.Index(fields=['user', 'is_read', 'is_archived'], name='api_workflo_user_id_959668_idx'),
        ),
    ]
