# Generated by Django 4.2.21 on 2025-06-26 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_saftfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SAFTFile',
        ),
    ]
