# Generated by Django 4.2.21 on 2025-06-26 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0050_saftfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição do Lote')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_batches', to='api.organization')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lote de Faturas',
                'verbose_name_plural': 'Lotes de Faturas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScannedInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_file', models.FileField(upload_to='invoice_uploads/%Y/%m/')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PROCESSING', 'A Processar'), ('REVIEW', 'Requer Revisão'), ('COMPLETED', 'Concluído'), ('ERROR', 'Erro')], db_index=True, default='PENDING', max_length=20)),
                ('processing_log', models.TextField(blank=True, help_text='Log de processamento ou mensagem de erro.', null=True)),
                ('raw_qr_code_data', models.CharField(blank=True, max_length=500, null=True)),
                ('nif_emitter', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('nif_acquirer', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('country_code', models.CharField(blank=True, max_length=2, null=True)),
                ('doc_type', models.CharField(blank=True, choices=[('FT', 'Fatura'), ('FS', 'Fatura Simplificada'), ('FR', 'Fatura-Recibo'), ('NC', 'Nota de Crédito'), ('ND', 'Nota de Débito'), ('OT', 'Outro')], max_length=5, null=True)),
                ('doc_date', models.DateField(blank=True, null=True)),
                ('doc_uid', models.CharField(blank=True, max_length=100, null=True)),
                ('atcud', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('taxable_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('vat_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('gross_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('edited_data', models.JSONField(blank=True, default=dict, help_text='Armazena correções feitas pelo utilizador.')),
                ('is_reviewed', models.BooleanField(default=False, help_text='Marcado como True após revisão do utilizador.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='api.invoicebatch')),
            ],
            options={
                'verbose_name': 'Fatura Digitalizada',
                'verbose_name_plural': 'Faturas Digitalizadas',
                'ordering': ['-created_at'],
            },
        ),
    ]
