# Generated by Django 4.2.21 on 2025-06-26 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_invoicebatch_scannedinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannedinvoice',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
