# Generated by Django 4.2.21 on 2025-06-28 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_scannedinvoice_original_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='source_scanned_invoice',
            field=models.ForeignKey(blank=True, help_text='A fatura que originou a criação desta tarefa de lançamento.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_tasks', to='api.scannedinvoice', verbose_name='Fatura Digitalizada de Origem'),
        ),
    ]
