# Generated by Django 4.2.21 on 2025-06-29 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_task_source_scanned_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='financial_health_score',
            field=models.IntegerField(blank=True, help_text="Calculated score (0-100) representing client's financial health.", null=True),
        ),
    ]
