# Generated by Django 4.2.21 on 2025-06-29 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_client_financial_health_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='compliance_risks',
            field=models.JSONField(blank=True, default=list, help_text='List of identified compliance risks.'),
        ),
    ]
