# Generated by Django 4.2.21 on 2025-06-29 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_client_revenue_opportunities'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='source_scanned_invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expense', to='api.scannedinvoice', verbose_name='Fatura Digitalizada de Origem'),
        ),
    ]
