# Generated by Django 4.2.21 on 2025-06-29 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_expense_source_scanned_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='churn_risk',
            field=models.CharField(blank=True, choices=[('LOW', 'Baixo'), ('MEDIUM', 'Médio'), ('HIGH', 'Alto')], default='LOW', max_length=10),
        ),
    ]
