# Generated by Django 4.2.21 on 2025-06-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_client_churn_risk'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstep',
            name='avg_completion_minutes',
            field=models.FloatField(blank=True, help_text='Average time in minutes to complete this step.', null=True),
        ),
    ]
