# Generated by Django 4.2.21 on 2025-06-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_workflowstep_avg_completion_minutes'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(condition=models.Q(('source_scanned_invoice__isnull', False)), fields=('source_scanned_invoice',), name='unique_task_per_scanned_invoice'),
        ),
    ]
