# Generated by Django 4.2.21 on 2025-07-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_organizationactionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflownotification',
            name='acted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflownotification',
            name='action_type',
            field=models.CharField(blank=True, choices=[('none', 'Nenhuma'), ('read', 'Lida'), ('dismissed', 'Descartada'), ('acted', 'Ação Tomada')], default='none', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='workflownotification',
            name='dismissed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
