# Generated by Django 4.2.21 on 2025-07-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_workflownotification_acted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsettings',
            name='digest_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='notification_types_enabled',
            field=models.JSONField(default=dict, help_text="Quais tipos de notificação o usuário deseja receber (ex: {'step_ready': True, ...})"),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='preferred_channels',
            field=models.JSONField(default=list, help_text="Canais preferidos para notificações (ex: ['in_app', 'email'])"),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='quiet_hours_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
