# docker-compose.prod.yml (Corrected for your structure)
version: '3.8'

services:
  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  backend:
    build:
      context: .                  # Use the root directory as the build context
      dockerfile: Dockerfile.backend # Specify the Dockerfile in the root
    command: >
      sh -c "echo 'Waiting for Redis...' && while ! nc -z redis 6379; do sleep 1; done; echo 'Redis started.' &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn backend.wsgi:application --bind 0.0.0.0:8000 --workers 3 --log-level info"
    env_file:
      - ./backend/.env
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    expose:
      - 8000

  celeryworker:
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: python -m celery -A backend.celery worker -l info
    env_file:
      - ./backend/.env
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped

  celerybeat:
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: python -m celery -A backend.celery beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file:
      - ./backend/.env
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped

  nginx:
    build:
      context: .                 # Use the root directory as the build context
      dockerfile: Dockerfile.nginx # Specify the Nginx Dockerfile in the root
      args:
        VITE_API_URL: /api
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped