version: '3.8'
services:
  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: >
      sh -c "echo 'Waiting for Redis...' && while ! nc -z redis 6379; do sleep 1; done; echo 'Redis started.' &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn backend.wsgi:application --bind 0.0.0.0:8000 --workers 3 --log-level info"
    env_file:
      - ./backend/.env
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    expose:
      - 8000
    volumes:
      - media_files:/app/media  # ADD THIS SHARED VOLUME

  celery:
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: >
      sh -c "echo 'Waiting for Redis...' && while ! nc -z redis 6379; do sleep 1; done; echo 'Redis started.' &&
             celery -A backend worker --loglevel=info --concurrency=2"
    env_file:
      - ./backend/.env
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - media_files:/app/media  # ADD THIS SHARED VOLUME

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: >
      sh -c "echo 'Waiting for Redis...' && while ! nc -z redis 6379; do sleep 1; done; echo 'Redis started.' &&
             celery -A backend beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    env_file:
      - ./backend/.env
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - media_files:/app/media  # ADD THIS SHARED VOLUME

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
      args:
        VITE_API_URL: /api
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

# ADD THIS VOLUMES SECTION
volumes:
  media_files: